# NumPy Basics: Fundamentals

This notebook covers the essential building blocks of NumPy — the library that powers nearly every ML and data science workflow in Python.

**Topics covered:**
1. What is NumPy & Why use it
2. Creating Arrays
3. Array Properties
4. Indexing & Slicing
5. Array Operations
6. Reshaping
7. Basic Statistics
8. ML Context

---
## 1. What is NumPy & Why Use It?

**NumPy** (Numerical Python) is the foundational library for scientific computing. It provides:
- Fast, memory-efficient **n-dimensional array** (`ndarray`)
- Vectorized operations (no manual loops needed)
- Linear algebra, random number generation, and Fourier transforms

### NumPy vs Python Lists

| Feature | Python List | NumPy Array |
|---------|------------|-------------|
| Data type | Can mix types | Homogeneous (same type) |
| Speed | Slow (interpreted loops) | Fast (C under the hood) |
| Memory | More overhead | Compact, contiguous memory |
| Operations | Manual loops | Element-wise by default |

Let's see the speed difference:

In [1]:
import numpy as np
import time

# Speed comparison: Python list vs NumPy array
py_list = list(range(1_000_000))
np_array = np.arange(1_000_000)

# Python list: element-wise multiplication with a loop
start = time.time()
result_list = [x * 2 for x in py_list]
print(f"Python list: {time.time() - start:.4f} seconds")

# NumPy array: vectorized multiplication
start = time.time()
result_array = np_array * 2
print(f"NumPy array: {time.time() - start:.4f} seconds")

Python list: 0.0654 seconds
NumPy array: 0.0034 seconds


NumPy is typically **10-100x faster** than equivalent Python loops because operations run in optimized C code.

---
## 2. Creating Arrays

There are many ways to create NumPy arrays depending on your needs.

In [2]:
# From a Python list
a = np.array([1, 2, 3, 4, 5])
print("From list:", a)

# 2D array from nested lists
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("2D array:\n", b)

From list: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


In [3]:
# Arrays filled with zeros or ones
zeros = np.zeros((3, 4))  # 3 rows, 4 columns of 0.0
ones = np.ones((2, 3))    # 2 rows, 3 columns of 1.0

print("Zeros:\n", zeros)
print("Ones:\n", ones)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# Constant-filled array
filled = np.full((3, 3), 7)
print("Filled with 7:\n", filled)

# Identity matrix
eye = np.eye(4)
print("Identity matrix:\n", eye)

Filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
#.arange — like Python range but returns an array
seq1 = np.arange(0, 10, 2)  # start, stop, step
print("arange:", seq1)

# linspace — evenly spaced numbers over a interval
seq2 = np.linspace(0, 1, 5)  # 5 points from 0 to 1 (inclusive)
print("linspace:", seq2)

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


In [6]:
# Random arrays
uniform = np.random.rand(3, 3)    # values from [0, 1)
normal = np.random.randn(3, 3)    # standard normal distribution
randint = np.random.randint(0, 10, size=(3, 4))  # random integers

print("Uniform:\n", uniform)
print("Normal:\n", normal)
print("Random integers:\n", randint)

Uniform:
 [[0.9576158  0.26865533 0.7206536 ]
 [0.56598609 0.71984441 0.4016809 ]
 [0.32364766 0.34331008 0.27188653]]
Normal:
 [[-0.38593428  0.09108053 -1.56475746]
 [-0.44964199 -2.34767645 -1.38621597]
 [ 0.27333956  0.10593232  0.98361296]]
Random integers:
 [[5 2 6 0]
 [4 0 0 8]
 [6 8 1 3]]


---
## 3. Array Properties

Every NumPy array carries metadata about its shape, size, and data type.

In [7]:
arr = np.array([[1.5, 2.3, 4.1],
                [5.0, 6.7, 8.2]])

print("Array:\n", arr)
print(f"Shape:      {arr.shape}")      # (rows, columns)
print(f"Dimensions: {arr.ndim}")        # number of dimensions
print(f"Size:       {arr.size}")        # total number of elements
print(f"Data type:  {arr.dtype}")       # data type of elements
print(f"Item size:  {arr.itemsize} bytes")  # bytes per element
print(f"Total bytes:{arr.nbytes} bytes")    # total memory usage

Array:
 [[1.5 2.3 4.1]
 [5.  6.7 8.2]]
Shape:      (2, 3)
Dimensions: 2
Size:       6
Data type:  float64
Item size:  8 bytes
Total bytes:48 bytes


Useful for checking: does my data have the right shape for the model I'm building?

---
## 4. Indexing & Slicing

Access elements, rows, columns, or subarrays — just like Python lists, but with more power.

In [8]:
# 1D indexing
arr = np.array([10, 20, 30, 40, 50])
print("Element at index 2:", arr[2])   # 30
print("Last element:", arr[-1])         # 50
print("Slice [1:4]:", arr[1:4])         # [20, 30, 40]

Element at index 2: 30
Last element: 50
Slice [1:4]: [20 30 40]


In [9]:
# 2D indexing — [row, column]
mat = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9, 10, 11, 12]])

print("Single element [1, 2]:", mat[1, 2])     # 7
print("First row:", mat[0, :])                  # [1, 2, 3, 4]
print("Second column:", mat[:, 1])              # [2, 6, 10]
print("Submatrix [0:2, 1:3]:\n", mat[0:2, 1:3])  # 2x2 block

Single element [1, 2]: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Submatrix [0:2, 1:3]:
 [[2 3]
 [6 7]]


In [10]:
# Boolean indexing — filter elements by condition
data = np.array([15, 22, 8, 42, 3, 31])
mask = data > 20

print("Mask:", mask)
print("Elements > 20:", data[mask])

# Direct filtering
print("Elements > 20:", data[data > 20])

# Useful: count how many satisfy a condition
print(f"Count > 20: {(data > 20).sum()}")

Mask: [False  True False  True False  True]
Elements > 20: [22 42 31]
Elements > 20: [22 42 31]
Count > 20: 3


---
## 5. Array Operations

NumPy applies operations **element-wise** by default — no loops needed.

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Element-wise operations
print("Add:    ", a + b)
print("Subtract:", b - a)
print("Multiply:", a * b)
print("Divide: ", b / a)
print("Power:   ", a ** 2)

Add:     [11 22 33 44]
Subtract: [ 9 18 27 36]
Multiply: [ 10  40  90 160]
Divide:  [10. 10. 10. 10.]
Power:    [ 1  4  9 16]


In [12]:
# Scalar operations — broadcast to every element
print("Add 10:", a + 10)
print("Multiply by 3:", a * 3)

# Common math functions
print("Square root:", np.sqrt(a))
print("Exponential:", np.exp(a))
print("Logarithm:", np.log(a))
print("Absolute:", np.abs(np.array([-1, 2, -3])))

Add 10: [11 12 13 14]
Multiply by 3: [ 3  6  9 12]
Square root: [1.         1.41421356 1.73205081 2.        ]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Logarithm: [0.         0.69314718 1.09861229 1.38629436]
Absolute: [1 2 3]


In [13]:
# Comparison operators return boolean arrays
scores = np.array([85, 92, 78, 95, 88])

print("Scores:", scores)
print(" >= 90:", scores >= 90)
print(" == 88:", scores == 88)
print("Count >= 90:", (scores >= 90).sum())

Scores: [85 92 78 95 88]
 >= 90: [False  True False  True False]
 == 88: [False False False False  True]
Count >= 90: 2


---
## 6. Reshaping

Change the shape of an array without changing its data — essential for preparing data for ML models.

In [14]:
arr = np.arange(12)
print("Original (1D):", arr, "-> shape:", arr.shape)

# Reshape to 2D
mat = arr.reshape(3, 4)
print("Reshaped (3x4):\n", mat)

# Reshape to 3D
cube = arr.reshape(2, 2, 3)
print("3D (2x2x3):\n", cube)

Original (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11] -> shape: (12,)
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3D (2x2x3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [15]:
# Use -1 to let NumPy infer the dimension
print("reshape(3, -1):\n", arr.reshape(3, -1))  # 3 rows, auto columns
print("reshape(-1, 4):\n", arr.reshape(-1, 4))  # auto rows, 4 columns

reshape(3, -1):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape(-1, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
# flatten vs ravel
mat = np.array([[1, 2], [3, 4]])

flat = mat.flatten()   # returns a COPY
rav = mat.ravel()      # returns a VIEW (more memory efficient)

# Transpose
print("Original:\n", mat)
print("Transposed:\n", mat.T)

Original:
 [[1 2]
 [3 4]]
Transposed:
 [[1 3]
 [2 4]]


---
## 7. Basic Statistics

Quick descriptive statistics — the first thing you do when exploring any dataset.

In [17]:
# Student exam scores
scores = np.array([78, 85, 92, 88, 76, 95, 89, 84, 91, 87])

print(f"Mean:     {scores.mean():.2f}")
print(f"Median:   {np.median(scores):.2f}")
print(f"Std Dev:  {scores.std():.2f}")
print(f"Variance: {scores.var():.2f}")
print(f"Min:      {scores.min()}")
print(f"Max:      {scores.max()}")
print(f"Sum:      {scores.sum()}")

Mean:     86.50
Median:   87.50
Std Dev:  5.68
Variance: 32.25
Min:      76
Max:      95
Sum:      865


In [18]:
# argmin / argmax — index of min/max
print(f"Index of max score: {scores.argmax()} -> score {scores[scores.argmax()]}")
print(f"Index of min score: {scores.argmin()} -> score {scores[scores.argmin()]}")

# Percentiles
print(f"25th percentile: {np.percentile(scores, 25):.2f}")
print(f"75th percentile: {np.percentile(scores, 75):.2f}")

Index of max score: 5 -> score 95
Index of min score: 4 -> score 76
25th percentile: 84.25
75th percentile: 90.50


In [19]:
# Axis-wise statistics on 2D arrays
grades = np.array([[85, 90, 78],   # student 1: 3 subjects
                   [92, 88, 95],   # student 2
                   [76, 81, 89]])  # student 3

print("Grades (students x subjects):\n", grades)
print("\nMean per student (axis=1):", grades.mean(axis=1))  # row-wise
print("Mean per subject (axis=0):", grades.mean(axis=0))   # column-wise

Grades (students x subjects):
 [[85 90 78]
 [92 88 95]
 [76 81 89]]

Mean per student (axis=1): [84.33333333 91.66666667 82.        ]
Mean per subject (axis=0): [84.33333333 86.33333333 87.33333333]


---
## 8. ML Context — Putting It Together

Here's how these basics connect to real ML workflows.

In [20]:
# Scenario: preparing features for a model

# Raw data: 5 samples, 3 features each (e.g., height, weight, age)
raw_data = [
    [170, 65, 25],
    [180, 80, 30],
    [165, 55, 22],
    [175, 70, 28],
    [160, 50, 20]
]

# Convert to NumPy array
X = np.array(raw_data, dtype=np.float64)
print("Feature matrix shape:", X.shape, "-> (samples, features)")
print("Data type:", X.dtype)
print("\nFeature matrix:\n", X)

Feature matrix shape: (5, 3) -> (samples, features)
Data type: float64

Feature matrix:
 [[170.  65.  25.]
 [180.  80.  30.]
 [165.  55.  22.]
 [175.  70.  28.]
 [160.  50.  20.]]


In [21]:
# Normalize features (min-max scaling to [0, 1])
X_min = X.min(axis=0)
X_max = X.max(axis=0)
X_normalized = (X - X_min) / (X_max - X_min)

print("Original:\n", X)
print("\nNormalized (min-max):\n", X_normalized)
print("\nCheck: min per feature =", X_normalized.min(axis=0))
print("Check: max per feature =", X_normalized.max(axis=0))

Original:
 [[170.  65.  25.]
 [180.  80.  30.]
 [165.  55.  22.]
 [175.  70.  28.]
 [160.  50.  20.]]

Normalized (min-max):
 [[0.5        0.5        0.5       ]
 [1.         1.         1.        ]
 [0.25       0.16666667 0.2       ]
 [0.75       0.66666667 0.8       ]
 [0.         0.         0.        ]]

Check: min per feature = [0. 0. 0.]
Check: max per feature = [1. 1. 1.]


In [22]:
# Standardize features (z-score: mean=0, std=1)
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
X_standardized = (X - X_mean) / X_std

print("Standardized:\n", X_standardized)
print("\nMean per feature (should be ~0):", X_standardized.mean(axis=0))
print("Std per feature (should be 1):", X_standardized.std(axis=0))

Standardized:
 [[ 0.          0.09365858  0.        ]
 [ 1.41421356  1.4985373   1.35581536]
 [-0.70710678 -0.84292723 -0.81348922]
 [ 0.70710678  0.56195149  0.81348922]
 [-1.41421356 -1.31122014 -1.35581536]]

Mean per feature (should be ~0): [0. 0. 0.]
Std per feature (should be 1): [1. 1. 1.]


In [23]:
# Creating a label array
y = np.array([0, 1, 0, 1, 0])  # 0 = not interested, 1 = interested

print("Samples class 0:", (y == 0).sum())
print("Samples class 1:", (y == 1).sum())

# Quick data exploration summary
print(f"\nDataset: {X.shape[0]} samples, {X.shape[1]} features")
print(f"Feature names: height, weight, age")
print(f"Label distribution: {dict(zip(*np.unique(y, return_counts=True)))}")

Samples class 0: 3
Samples class 1: 2

Dataset: 5 samples, 3 features
Feature names: height, weight, age
Label distribution: {np.int64(0): np.int64(3), np.int64(1): np.int64(2)}


---
## Summary

You now know:
- How to create arrays from lists, zeros/ones, ranges, and random generators
- How to inspect array shape, dtype, and size
- How to index, slice, and filter with booleans
- How to do element-wise math and comparisons
- How to reshape, flatten, and transpose arrays
- How to compute basic statistics with and without axes
- How these basics apply to preparing ML data

**Next:** `02-Intermediate.ipynb` — broadcasting, linear algebra, combining arrays, and more.