In [2]:
import numpy as np
import time

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape, arr.ndim, arr.size, arr.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) 1 5 int64


In [4]:
size = 10_000_000

# python list
py_list = list(range(size)) # [0, 1, 2, ..., size-1]
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print("Python list time:", end - start, "seconds")

# numpy array
np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2 # This is vectorized operation
end = time.time()
print("Numpy array time:", end - start, "seconds")

Python list time: 0.8878257274627686 seconds
Numpy array time: 0.02249622344970703 seconds


In [5]:
# Memory usage
import sys

print("Python list memory usage:", sys.getsizeof(py_list), "bytes")
print("Numpy array memory usage:", np_array.nbytes, "bytes")

Python list memory usage: 80000056 bytes
Numpy array memory usage: 80000000 bytes


In [6]:
# Creating numpy arrays
arr = np.array([1, 2, 3, 4, 5])
print("1D array:", arr, "Type:", type(arr), "Shape:", arr.shape, "Dimensions:", arr.ndim, "Size:", arr.size, "Data type:", arr.dtype)

# Creating 2D arrays
arr_2d = np.array([
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]
                  ])
print("2D array:", arr_2d, "Type:", type(arr_2d), "Shape:", arr_2d.shape, "Dimensions:", arr_2d.ndim, "Size:", arr_2d.size, "Data type:", arr_2d.dtype)

# Creating 3D arrays
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("3D array:", arr_3d, "Type:", type(arr_3d), "Shape:", arr_3d.shape, "Dimensions:", arr_3d.ndim, "Size:", arr_3d.size, "Data type:", arr_3d.dtype)

1D array: [1 2 3 4 5] Type: <class 'numpy.ndarray'> Shape: (5,) Dimensions: 1 Size: 5 Data type: int64
2D array: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] Type: <class 'numpy.ndarray'> Shape: (4, 3) Dimensions: 2 Size: 12 Data type: int64
3D array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] Type: <class 'numpy.ndarray'> Shape: (2, 2, 3) Dimensions: 3 Size: 12 Data type: int64


In [ ]:
# Create arrays with zeros, ones, and a specific value
zeros_array = np.zeros((3, 4))  # 3x4 array of zeros
print("Zeros array:\n", zeros_array, "Type:", type(zeros_array), "Shape:", zeros_array.shape, "Dimensions:", zeros_array.ndim, "Size:", zeros_array.size, "Data type:", zeros_array.dtype)
ones_array = np.ones((2, 5), dtype=int)    # 2x5 array of ones
print("Ones array:\n", ones_array, "Type:", type(ones_array), "Shape:", ones_array.shape, "Dimensions:", ones_array.ndim, "Size:", ones_array.size, "Data type:", ones_array.dtype)
specific_value_array = np.full((2, 3), 9)  # 2x3 array of nines
print("Specific value array:\n", specific_value_array, "Type:", type(specific_value_array), "Shape:", specific_value_array.shape, "Dimensions:", specific_value_array.ndim, "Size:", specific_value_array.size, "Data type:", specific_value_array.dtype)

# Identity matrix
identity_matrix = np.eye(4, dtype=int)  # 4x4 identity matrix
print("Identity matrix:\n", identity_matrix, "Type:", type(identity_matrix), "Shape:", identity_matrix.shape, "Dimensions:", identity_matrix.ndim, "Size:", identity_matrix.size, "Data type:", identity_matrix.dtype)

# Range function
range_array = np.arange(0, 10, 2)  # Array from 0 to 10 with step 2
print("Range array:", range_array, "Type:", type(range_array), "Shape:", range_array.shape, "Dimensions:", range_array.ndim, "Size:", range_array.size, "Data type:", range_array.dtype)

# Linspace function
linspace_array = np.linspace(0, 100, 5)  # 5 evenly spaced numbers from 0 to 100
print("Linspace array:", linspace_array, "Type:", type(linspace_array), "Shape:", linspace_array.shape, "Dimensions:", linspace_array.ndim, "Size:", linspace_array.size, "Data type:", linspace_array.dtype)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] Type: <class 'numpy.ndarray'> Shape: (3, 4) Dimensions: 2 Size: 12 Data type: float64
Ones array:
 [[1 1 1 1 1]
 [1 1 1 1 1]] Type: <class 'numpy.ndarray'> Shape: (2, 5) Dimensions: 2 Size: 10 Data type: int64
Specific value array:
 [[9 9 9]
 [9 9 9]] Type: <class 'numpy.ndarray'> Shape: (2, 3) Dimensions: 2 Size: 6 Data type: int64
Identity matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] Type: <class 'numpy.ndarray'> Shape: (4, 4) Dimensions: 2 Size: 16 Data type: int64
Range array: [0 2 4 6 8] Type: <class 'numpy.ndarray'> Shape: (5,) Dimensions: 1 Size: 5 Data type: int64
Linspace array: [  0.  25.  50.  75. 100.] Type: <class 'numpy.ndarray'> Shape: (5,) Dimensions: 1 Size: 5 Data type: float64


In [23]:
# All Properties of numpy arrays
print("zeros_array:", zeros_array)
print("Zeros array properties:")
print("Shape:", zeros_array.shape)
print("Dimensions:", zeros_array.ndim)
print("Size:", zeros_array.size)
print("Data type:", zeros_array.dtype)

int_zeros_array = zeros_array.astype(int)
print("Converted zeros_array to int:", int_zeros_array)
print("Data Type:", int_zeros_array.dtype)

zeros_array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zeros array properties:
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: float64
Converted zeros_array to int: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Data Type: int64


In [30]:
# Operations on numpy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 1:\n", arr1, "Shape:", arr1.shape)
# Reshaping the array
reshaped_arr1 = arr1.reshape(3, 2)
print("Reshaped Array 1:\n", reshaped_arr1, "Shape:", reshaped_arr1.shape)
# Flattening the array
flattened_arr1 = arr1.flatten()
print("Flattened Array 1:\n", flattened_arr1, "Shape:", flattened_arr1.shape)
# indexing and fancy indexing
print("Normal Indexing:")
# 1d array indexing
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr_1d)
print("Element at index 2:", arr_1d[2])
# 2d array indexing
print("2D Array:\n", arr1)
print("Element at row 1, column 2:", arr1[1, 2])
print("Fancy Indexing:")
# Fancy indexing with 1D array
fancy_indexed_arr = arr_1d[[0, 2, 4]]
print("Fancy Indexed Array (1D) accessing elements at indices [0, 2, 4]:", fancy_indexed_arr)
# Fancy indexing with 2D array
fancy_indexed_arr_2d = arr1[[0, 1], [1, 2]]  # Accessing elements at (0,1) and (1,2)
print("Fancy Indexed Array (2D) accessing elements at (0,1) and (1,2):", fancy_indexed_arr_2d)

# Boolean Indexing
print("Boolean Indexing:")
# Create a boolean mask
bool_mask = arr_1d > 25
print("Boolean Mask:", bool_mask)
# Apply the boolean mask to the array
bool_indexed_arr = arr_1d[bool_mask]
print("Boolean Indexed Array:", bool_indexed_arr)

# Slicing
print("Slicing:")
print("Elements from index 1 to 4:", arr_1d[1:5])
print("Elements from row 0 to 1, column 0 to 2:", arr1[0:2, 0:3])


Array 1:
 [[1 2 3]
 [4 5 6]] Shape: (2, 3)
Reshaped Array 1:
 [[1 2]
 [3 4]
 [5 6]] Shape: (3, 2)
Flattened Array 1:
 [1 2 3 4 5 6] Shape: (6,)
Normal Indexing:
1D Array: [10 20 30 40 50]
Element at index 2: 30
2D Array:
 [[1 2 3]
 [4 5 6]]
Element at row 1, column 2: 6
Fancy Indexing:
Fancy Indexed Array (1D) accessing elements at indices [0, 2, 4]: [10 30 50]
Fancy Indexed Array (2D) accessing elements at (0,1) and (1,2): [2 6]
Boolean Indexing:
Boolean Mask: [False False  True  True  True]
Boolean Indexed Array: [30 40 50]
Slicing:
Elements from index 1 to 4: [20 30 40 50]
Elements from row 0 to 1, column 0 to 2: [[1 2 3]
 [4 5 6]]


In [33]:
# Copy vs View
print("Copy vs View:")
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]  # This creates a copy of the sublist, not a view. Changes to sub_list will not affect nums.
print("Original list:", nums)
print("Sublist (copy):", sub_list)
sub_list[0] = 99
print("Modified sublist:", sub_list)
print("Original list after modifying sublist:", nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:4]  # This creates a view of the original array
print("Original Numpy array:", arr)
print("Subarray (view):", sub_arr)
sub_arr[0] = 99
print("Modified subarray:", sub_arr)
print("Original Numpy array after modifying subarray:", arr)

# If we want to create a copy of the subarray, we can use the copy() method
sub_arr_copy = arr[1:4].copy()  # This creates a copy of the subarray
print("Subarray copy:", sub_arr_copy)

Copy vs View:
Original list: [1, 2, 3, 4, 5]
Sublist (copy): [2, 3]
Modified sublist: [99, 3]
Original list after modifying sublist: [1, 2, 3, 4, 5]
Original Numpy array: [1 2 3 4 5]
Subarray (view): [2 3 4]
Modified subarray: [99  3  4]
Original Numpy array after modifying subarray: [ 1 99  3  4  5]
Subarray copy: [99  3  4]
